# goal
geometry_msgs/PoseStamped pose
# 0 open, 1 closed
float32 gripper_position
---
# result
bool success
---
# feedback
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration movement_time
# progress from 0 to 1
float32 progress