# From navigation2/nav2_msgs
# goal
geometry_msgs/PoseStamped pose
---
# result
std_msgs/Empty result
---
# feedback
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
int16 number_of_recoveries
float32 distance_remaining