byte WHEELCHAIR = 0
byte ROLLATOR = 1
byte HOSPITALBED = 2
byte CHARGINGSTATION = 3

byte UNPAIR = 0
byte PAIR = 1

# action goal
byte device_type
byte pairing_mode
---
# action result
bool success
---
# action feedback
# progress from 0 to 1
float32 progress